// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkBaGE1sHvr2b3RD9CV0J5kYG0fwS6n_U',
    appId: '1:659682569217:web:3208cd83695d26b79fa400',
    messagingSenderId: '659682569217',
    projectId: 'mini-project-acaf2',
    authDomain: 'mini-project-acaf2.firebaseapp.com',
    storageBucket: 'mini-project-acaf2.firebasestorage.app',
    measurementId: 'G-BWK66QFXGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VkjBPn2GTFRWckT9nqEpaOyLXsQ6Qm8',
    appId: '1:659682569217:android:2b1480399165946a9fa400',
    messagingSenderId: '659682569217',
    projectId: 'mini-project-acaf2',
    storageBucket: 'mini-project-acaf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmI7UWPlooTHW4-WZDxT6upLpPw_AJXEI',
    appId: '1:659682569217:ios:1a0fdd78fdca052b9fa400',
    messagingSenderId: '659682569217',
    projectId: 'mini-project-acaf2',
    storageBucket: 'mini-project-acaf2.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmI7UWPlooTHW4-WZDxT6upLpPw_AJXEI',
    appId: '1:659682569217:ios:1a0fdd78fdca052b9fa400',
    messagingSenderId: '659682569217',
    projectId: 'mini-project-acaf2',
    storageBucket: 'mini-project-acaf2.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkBaGE1sHvr2b3RD9CV0J5kYG0fwS6n_U',
    appId: '1:659682569217:web:8cddbb9ec24530b99fa400',
    messagingSenderId: '659682569217',
    projectId: 'mini-project-acaf2',
    authDomain: 'mini-project-acaf2.firebaseapp.com',
    storageBucket: 'mini-project-acaf2.firebasestorage.app',
    measurementId: 'G-4JDV3FKHH4',
  );
}
